language: cpp
compiler: gcc
before_install:
   - echo "yes" | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
   - sudo apt-get update -qq
   #- sudo apt-get install libtool-2.4.2
   - sudo apt-get install -qq g++-4.8
   - export CXX="g++-4.8"
   - sudo apt-get install cmake
   - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-net-dev
   #need to build sdl2_gfx
   - curl -O http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
   - tar -xzvf SDL2_gfx-1.0.1.tar.gz
   - cd SDL2_gfx-1.0.1
   - ./autogen.sh
   - ./configure
   - make
   - sudo make install
   - cd ..
script: 
   - mkdir build
   - cd build
   - cmake ../ -DCMAKE_BUILD_TYPE:STRING=Debug -DTRAVIS_BUILD:STRING=Yes
   - make